# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: unittests
        name: run unit tests
        entry: python -m unittest
        language: system
        pass_filenames: false
        verbose: true
        args: ["discover", "-s", "tests"]
